<%@ page contentType="text/html; charset=UTF-8" language="java" pageEncoding="UTF-8" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<spring:message code="face_recognition_management_system" var="face_recognition_management_system"/>
<spring:message code="login" var="login"/>
<spring:message code="hello" var="hello"/>
<spring:message code="change_password" var="change_password"/>
<spring:message code="sign_out" var="sign_out"/>
<spring:message code="people_management" var="people_management"/>
<spring:message code="people_list" var="people_list"/>
<spring:message code="determine" var="determine"/>
<spring:message code="cancel_lang" var="cancel_lang"/>
<spring:message code="new_password" var="new_password"/>
<spring:message code="old_password" var="old_password"/>
<spring:message code="enter_new_password" var="enter_new_password"/>
<spring:message code="enter_old_password" var="enter_old_password"/>
<spring:message code="delete_record" var="delete_record"/>
<spring:message code="tick_record" var="tick_record"/>
<spring:message code="delete_selected_record" var="delete_selected_record"/>
<spring:message code="please_enter_the_search_content" var="search_content"/>
<spring:message code="record_management" var="record_management"/>
<spring:message code="record_list" var="record_list"/>
<spring:message code="delete_in_batches" var="delete_in_batches"/>
<spring:message code="search" var="search"/>
<spring:message code="id" var="id"/>
<spring:message code="name" var="name"/>
<spring:message code="device" var="device"/>
<spring:message code="recognition_mode" var="mode"/>
<spring:message code="human_face" var="human_face"/>
<spring:message code="id_card" var="id_card"/>
<spring:message code="job_number" var="job_number"/>
<spring:message code="face_and_card" var="face_and_card"/>
<spring:message code="face_and_num" var="face_and_num"/>
<spring:message code="please_put_the_avatar_in_the_box" var="avatar_box_lang"/>
<spring:message code="device_name" var="device_name"/>
<spring:message code="device_id" var="device_id"/>
<spring:message code="pass_time" var="pass_time"/>
<spring:message code="unlimited_number_of_times" var="unlimited_number_time"/>
<spring:message code="passage_period" var="passage_period"/>
<spring:message code="infinite_time" var="infinite_time"/>
<spring:message code="operation" var="operation"/>
<spring:message code="modify" var="modify"/>
<spring:message code="ban" var="ban"/>
<spring:message code="people_id" var="people_id"/>
<spring:message code="registration_time" var="registration_time"/>
<spring:message code="name" var="name"/>
<spring:message code="the_bottom_picture" var="the_bottom_picture"/>
<spring:message code="save" var="save"/>
<spring:message code="delete" var="delete"/>
<spring:message code="please_enter_the_name" var="input_name_lang"/>
<spring:message code="please_enter_the_number" var="input_job_number_lang"/>
<spring:message code="choose_picture" var="choose_picture_lang"/>
<spring:message code="add" var="add"/>
<spring:message code="this_type_of_file_is_not_supported" var="dont_supported"/>
<spring:message code="upload_image_is_too_large" var="image_large"/>
<spring:message code="only_one_picture_can_be_selected" var="picture_selected"/>
<spring:message code="uploading" var="uploading"/>
<spring:message code="select_picture" var="select_picture"/>
<spring:message code="image_exceed" var="image_exceed"/>
<spring:message code="please_enter_the_name" var="enter_name"/>
<spring:message code="are_you_sure_you_want_to_delete_this_employee" var="sure_delete"/>
<spring:message code="is_this_device_prohibited_from_passing_the_employee" var="sure_ban"/>
<spring:message code="please_fill_in_the_number_of_passes" var="fill_number_passes"/>
<spring:message code="please_fill_in_the_passable_time" var="fill_passable_time"/>
<spring:message code="basic_Information" var="basic_info"/>
<spring:message code="accessible_device" var="accessible_device"/>
<spring:message code="people_id" var="people_id_lang"/>
<spring:message code="next_page" var="next_page_lang"/>
<spring:message code="previous_page" var="previous_page_lang"/>
<spring:message code="add_people" var="add_people"/>
<spring:message code="recognition_picture" var="reg_picture"/>
<spring:message code="admin_login" var="admin_login"/>
<spring:message code="equ_management_lang" var="equ_management"/>
<spring:message code="group_management_lang" var="group_management"/>
<spring:message code="add_device" var="add_device"/>
<spring:message code="group_id_lang" var="group_id_lang"/>
<spring:message code="create_time" var="create_time"/>
<spring:message code="group_name" var="group_name"/>
<spring:message code="devise_serial_number" var="devise_serial_number"/>
<spring:message code="online_lang" var="online"/>
<spring:message code="offline_lang" var="offline"/>
<spring:message code="remove_lang" var="remove_lang"/>
<spring:message code="enter_person_keyword" var="enter_person_keyword"/>
<spring:message code="optional_staff" var="optional_staff"/>
<spring:message code="authorized_personnel" var="authorized_personnel"/>
<spring:message code="enter_device_keyword" var="enter_device_keyword"/>
<spring:message code="optional_device" var="optional_device"/>
<spring:message code="authorize_device" var="authorize_device"/>
<spring:message code="specified_number" var="specified_number"/>
<spring:message code="specified_time" var="specified_time"/>
<spring:message code="end_date" var="end_date"/>
<spring:message code="start_date" var="start_date"/>
<spring:message code="author_access" var="author_access"/>
<spring:message code="no_entry" var="no_entry"/>
<spring:message code="to_lang" var="to_lang"/>
<spring:message code="group_list" var="group_list"/>
<spring:message code="device_list" var="device_list"/>
<spring:message code="assign_permissions" var="assign_permission"/>
<spring:message code="add_authorized_person" var="add_authorized_person"/>
<spring:message code="add_authorized_device" var="add_authorized_device"/>
<spring:message code="delete_group" var="delete_group"/>
<spring:message code="add_group" var="add_group"/>
<spring:message code="enter_group" var="enter_group"/>
<spring:message code="modify_access" var="modify_access"/>
<spring:message code="open_condition" var="open_condition"/>
<spring:message code="please_choose" var="please_choose"/>
<spring:message code="online" var="choose_online"/>
<spring:message code="sn_number" var="sn_number"/>
<spring:message code="author_code" var="author_code"/>
<spring:message code="active_time" var="active_time"/>
<spring:message code="last_online" var="last_online"/>
<spring:message code="last_offline" var="last_offline"/>
<spring:message code="author_id" var="author_id"/>
<spring:message code="success_text" var="success_text"/>
<spring:message code="fail_text" var="fail_text"/>
<spring:message code="offline_delete_device" var="offline_delete_device"/>
<spring:message code="note_delete_device" var="note_delete_device"/>
<spring:message code="device_not_activated" var="device_not_activated"/>
<spring:message code="active_state" var="active_state"/>
<spring:message code="activated" var="activated"/>
<spring:message code="inactivated" var="inactivated"/>
<spring:message code="activation" var="activation"/>
<spring:message code="online_status" var="online_status"/>
<spring:message code="activated_device" var="activated_device"/>
<spring:message code="function_config" var="function_config"/>
<spring:message code="author_person" var="author_person"/>
<spring:message code="device_cannot_empty" var="device_cannot_empty"/>